project_id = "pxyzuhgqcgaljkcvnmel"

[functions.ai-betting-search]
verify_jwt = false

[functions.fetch-team-logo]
verify_jwt = false

[functions.populate-college-logos]
verify_jwt = false

[functions.whop-auth]
verify_jwt = false

[functions.whop-list-channels]
verify_jwt = false

[functions.whop-share-message]
verify_jwt = false
